use intelligentdocument;
INSERT INTO document_type (title) VALUES ('ID Card');
INSERT INTO document_type (title) VALUES ('Passport');
INSERT INTO document_type (title) VALUES ('Driver License');
INSERT INTO document_type (title) VALUES ('Birth Certificate');
INSERT INTO document_type (title) VALUES ('Marriage Certificate');
INSERT INTO document_type (title) VALUES ('Divorce Certificate');
INSERT INTO document_type (title) VALUES ('Police Certificate');
INSERT INTO document_type (title) VALUES ('Military Service Record');
INSERT INTO document_type (title) VALUES ('Travel Document');
INSERT INTO document_type (title) VALUES ('Visa');
INSERT INTO document_type (title) VALUES ('Residence Permit');
INSERT INTO document_type (title) VALUES ('Work Permit');
INSERT INTO document_type (title) VALUES ('Insurance Card');
INSERT INTO document_type (title) VALUES ('Social Security Card');
INSERT INTO document_type (title) VALUES ('Tax ID Number');
INSERT INTO document_type (title) VALUES ('Bank Account Statement');
INSERT INTO document_type (title) VALUES ('Credit Card Statement');
INSERT INTO document_type (title) VALUES ('Utility Bill');
INSERT INTO document_type (title) VALUES ('Rental Agreement');
INSERT INTO document_type (title) VALUES ('Property Deed');
INSERT INTO document_type (title) VALUES ('Vehicle Registration');
INSERT INTO document_type (title) VALUES ('Vehicle Insurance');
INSERT INTO document_type (title) VALUES ('Vehicle Inspection Report');
INSERT INTO document_type (title) VALUES ('Medical Record');
INSERT INTO document_type (title) VALUES ('Prescription');
INSERT INTO document_type (title) VALUES ('Dental Record');
INSERT INTO document_type (title) VALUES ('Eye Exam Record');
INSERT INTO document_type (title) VALUES ('Vaccination Record');
INSERT INTO document_type (title) VALUES ('Blood Test Result');
INSERT INTO document_type (title) VALUES ('X-ray Result');
INSERT INTO document_type (title) VALUES ('Lab Test Result');
INSERT INTO document_type (title) VALUES ('Allergy Record');
INSERT INTO document_type (title) VALUES ('Medical Certificate');
INSERT INTO document_type (title) VALUES ('Employment Certificate');
INSERT INTO document_type (title) VALUES ('Education Certificate');
INSERT INTO document_type (title) VALUES ('Training Certificate');
INSERT INTO document_type (title) VALUES ('Qualification Certificate');
INSERT INTO document_type (title) VALUES ('Award Certificate');
INSERT INTO document_type (title) VALUES ('Membership Card');
INSERT INTO document_type (title) VALUES ('Pass Card');
INSERT INTO document_type (title) VALUES ('Library Card');
INSERT INTO document_type (title) VALUES ('Gym Membership Card');
INSERT INTO document_type (title) VALUES ('Club Membership Card');
INSERT INTO document_type (title) VALUES ('Loyalty Card');
INSERT INTO document_type (title) VALUES ('Gift Card');
INSERT INTO document_type (title) VALUES ('Coupon');
INSERT INTO document_type (title) VALUES ('Ticket');
INSERT INTO document_type (title) VALUES ('Invitation Card');
INSERT INTO document_type (title) VALUES ('Event Pass');
INSERT INTO document_type (title) VALUES ('Concert Ticket');
INSERT INTO document_type (title) VALUES ('Movie Ticket');
INSERT INTO document_type (title) VALUES ('Parking Pass');
INSERT INTO document_type (title) VALUES ('Toll Pass');
INSERT INTO document_type (title) VALUES ('Membership Pass');
INSERT INTO document_type (title) VALUES ('ID Badge');
INSERT INTO document_type (title) VALUES ('Visitor');
INSERT INTO document_type (title) VALUES ('Security Badge');
INSERT INTO document_type (title) VALUES ('Access Card');
INSERT INTO document_type (title) VALUES ('Name Tag');
INSERT INTO document_type (title) VALUES ('Business Card');
INSERT INTO document_type (title) VALUES ('Logo');
INSERT INTO document_type (title) VALUES ('Letterhead');
INSERT INTO document_type (title) VALUES ('Envelope');
INSERT INTO document_type (title) VALUES ('Invoice');
INSERT INTO document_type (title) VALUES ('Receipt');
INSERT INTO document_type (title) VALUES ('Purchase Order');
INSERT INTO document_type (title) VALUES ('Bill of Lading');
INSERT INTO document_type (title) VALUES ('Shipping Label');
INSERT INTO document_type (title) VALUES ('Inventory Record');
INSERT INTO document_type (title) VALUES ('Product Catalog');
INSERT INTO document_type (title) VALUES ('Marketing Material');
INSERT INTO document_type (title) VALUES ('Sales Report');
INSERT INTO document_type (title) VALUES ('Financial Statement');
INSERT INTO document_type (title) VALUES ('Tax Return');
INSERT INTO document_type (title) VALUES ('Audit Report');
INSERT INTO document_type (title) VALUES ('Insurance Policy');
INSERT INTO document_type (title) VALUES ('Lease Agreement');
INSERT INTO document_type (title) VALUES ('Service Contract');
INSERT INTO document_type (title) VALUES ('Maintenance Agreement');
INSERT INTO document_type (title) VALUES ('Non-Disclosure Agreement');
INSERT INTO document_type (title) VALUES ('Employment Agreement');
INSERT INTO document_type (title) VALUES ('Contractor Agreement');
INSERT INTO document_type (title) VALUES ('Partnership Agreement');
INSERT INTO document_type (title) VALUES ('Bylaws');
INSERT INTO document_type (title) VALUES ('Articles of Incorporation');
INSERT INTO document_type (title) VALUES ('Shareholder Agreement');
INSERT INTO document_type (title) VALUES ('Operating Agreement');
INSERT INTO document_type (title) VALUES ('Business Plan');
INSERT INTO document_type (title) VALUES ('Marketing Plan');
INSERT INTO document_type (title) VALUES ('Sales Plan');
INSERT INTO document_type (title) VALUES ('Financial Plan');
INSERT INTO document_type (title) VALUES ('Strategic Plan');
INSERT INTO document_type (title) VALUES ('Project Plan');
INSERT INTO document_type (title) VALUES ('Training Plan');
INSERT INTO document_type (title) VALUES ('Quality Control Plan');
INSERT INTO document_type (title) VALUES ('Risk Management Plan');
INSERT INTO document_type (title) VALUES ('Disaster Recovery Plan');
INSERT INTO document_type (title) VALUES ('Emergency Evacuation Plan');
INSERT INTO document_type (title) VALUES ('Occupational Health and Safety Plan');
INSERT INTO document_type (title) VALUES ('Environmental Plan');
INSERT INTO document_type (title) VALUES ('Social Responsibility Plan');
INSERT INTO document_type (title) VALUES ('Annual Report');
INSERT INTO document_type (title) VALUES ('Newsletter');
INSERT INTO document_type (title) VALUES ('Press Release');
INSERT INTO document_type (title) VALUES ('Brochure');
INSERT INTO document_type (title) VALUES ('Catalog');
INSERT INTO document_type (title) VALUES ('Manual');
INSERT INTO document_type (title) VALUES ('Guide');
INSERT INTO document_type (title) VALUES ('Tutorial');
INSERT INTO document_type (title) VALUES ('User Documentation');
INSERT INTO document_type (title) VALUES ('Technical Documentation');
INSERT INTO document_type (title) VALUES ('Policy Manual');
INSERT INTO document_type (title) VALUES ('Procedure Manual');
INSERT INTO document_type (title) VALUES ('Employee Handbook');
INSERT INTO document_type (title) VALUES ('Training Manual');
INSERT INTO document_type (title) VALUES ('Reference Book');
INSERT INTO document_type (title) VALUES ('Textbook');
INSERT INTO document_type (title) VALUES ('Novel');